"""
Monte Carlo sampling of road-restoration duration scenarios.

Repair time is uncertain, so instead of committing to a single estimate we draw
many equally plausible "scenarios" and later optimize against the whole set. A
scenario is one joint realization of how long every disrupted road segment takes
to repair, measured in discrete time slots, returned as a dict
{edge_id: duration_in_slots}.

Durations are sampled per LEVEL, where a level is the pair (road_class,
severity): segments that share the same road class and damage severity are
treated as interchangeable, so all of them receive the same drawn duration
within a given scenario. Each per-level draw combines a base repair time (from a
per-level support set, i.e. the set of plausible base durations for that road
class and severity) with a crew-efficiency factor eta (a multiplier for how
fast the repair crew works relative to nominal).
"""

import math

import numpy as np

import config as P


def sample_scenarios(disrupted, M=P.M_SCENARIOS, seed=P.SEED):
    """Draw M restoration-duration scenarios for the disrupted segments.

    `disrupted` is a DataFrame with columns edge_id, road_class, and severity.
    Returns a list of M dicts; scenario[m][edge_id] is that segment's realized
    repair duration in time slots. Because every segment of the same
    (road_class, severity) level shares one duration within a scenario, a
    duration is drawn once per distinct level and then broadcast to all of that
    level's segments. A fixed seed makes the whole sample reproducible.

    When config.EVAL_SAMPLING == "lhs" the draw is delegated to saa_lhs_sample: the SAME per-level
    duration distribution, sampled by probability-stratified Latin Hypercube instead of i.i.d., so
    M=50 covers the uncertainty space evenly and estimates E[F] with lower variance. It is a change
    of ruler (see the config note), so every method must be re-scored after flipping it.
    """
    if getattr(P, "EVAL_SAMPLING", "iid") == "lhs":
        return saa_lhs_sample(disrupted, M, np.random.RandomState(seed))
    rng = np.random.default_rng(seed)
    rows = list(disrupted.itertuples(index=False))
    # Enumerate the distinct (road_class, severity) levels present; sorting keeps
    # the draw order deterministic so a given seed always yields the same sample.
    levels = sorted({(r.road_class, int(r.severity)) for r in rows})
    scenarios = []
    for _ in range(M):
        # Draw one duration per level, then assign it to every segment of that level.
        lvl_dur = {}
        for lvl in levels:
            # Pick a plausible base repair time and an independent crew-efficiency
            # multiplier for this level in this scenario.
            base = int(rng.choice(P.DURATION_SUPPORT[lvl]))
            eta = float(rng.choice(P.ETA))
            # Scale the base time by crew efficiency and round to whole slots,
            # flooring at one so no repair is treated as instantaneous.
            lvl_dur[lvl] = max(1, int(round(base * eta)))
        scenarios.append({int(r.edge_id): lvl_dur[(r.road_class, int(r.severity))] for r in rows})
    return scenarios


def expected_durations(disrupted):
    """Expected repair duration of every disrupted segment under the FULL duration model, i.e.
    the mean over every outcome the model can produce rather than over a particular sample.

    A duration is generated by drawing a base time uniformly from that level's support set and a
    crew-efficiency multiplier uniformly from ETA, then rounding their product to whole slots and
    flooring at one, exactly as sample_scenarios does. Both draws range over a handful of values,
    so the expectation is computed by ENUMERATING the whole product of the two supports rather
    than by averaging a sample; the result therefore carries no sampling error and does not depend
    on the seed or on how many scenarios happen to be drawn.

    Returns {edge_id: expected duration in slots} as floats. A ranker that divides by these values
    stays a here-and-now rule, because nothing about it depends on which realization occurs.
    """
    per_level = {}
    for lvl, support in P.DURATION_SUPPORT.items():
        outcomes = [max(1, int(round(base * eta))) for base in support for eta in P.ETA]
        per_level[lvl] = float(np.mean(outcomes))
    return {int(r.edge_id): per_level[(r.road_class, int(r.severity))]
            for r in disrupted.itertuples(index=False)}


def nominal_durations(disrupted, segments=None):
    """The single duration vector the searching solvers optimize against: each segment's expected
    repair time, rounded to whole slots.

    expected_durations is exact but generally fractional, whereas every solver that reasons about
    WHEN a crew is occupied needs whole slots. Exact halves are rounded UP rather than by Python's
    round-half-to-even, so a repair is never modelled as faster than it is expected to be; with the
    current support sets the half cases (2.5 and 4.5 slots) are the common ones, and rounding them
    down would make the nominal world systematically optimistic.

    Every solver that searches on a nominal instance draws it from HERE, so the MILP and the
    metaheuristics are guaranteed to be optimizing against the same world; a second definition
    elsewhere would silently make their results incomparable. `segments` optionally restricts the
    result to the segments actually being scheduled.
    """
    exp_dur = expected_durations(disrupted)
    keys = exp_dur if segments is None else segments
    return {e: max(1, int(math.floor(exp_dur[e] + 0.5))) for e in keys}


def draw_durations(disrupted, rng):
    """One duration realization {edge_id: slots} under the SAME generative law as
    sample_scenarios: per (road_class, severity) level, a base time uniform on that level's
    support and an efficiency multiplier uniform on ETA, rounded to whole slots with a floor of
    one, the draw SHARED by every segment of the level.

    Exists for training-time world sampling (the stochastically-trained RL draws a fresh
    realization each episode). It deliberately duplicates sample_scenarios' six lines instead of
    being called by it: sample_scenarios feeds a fixed seed to a private generator and any change
    to its internal draw order would silently change the frozen evaluation sample, so that
    function stays untouched and this one takes the CALLER's rng. Keep the two laws identical;
    a divergence would make the training distribution differ from the evaluation distribution."""
    rows = list(disrupted.itertuples(index=False))
    levels = sorted({(r.road_class, int(r.severity)) for r in rows})
    lvl_dur = {}
    for lvl in levels:
        base = int(rng.choice(P.DURATION_SUPPORT[lvl]))
        eta = float(rng.choice(P.ETA))
        lvl_dur[lvl] = max(1, int(round(base * eta)))
    return {int(r.edge_id): lvl_dur[(r.road_class, int(r.severity))] for r in rows}


def saa_lhs_sample(disrupted, n, rng):
    """n duration scenarios by PROBABILITY-STRATIFIED Latin Hypercube Sampling over the per-level
    duration marginals -- a lower-variance stand-in for n i.i.d. draw_durations calls, for the FIXED
    SAA training sample.

    Same generative law as draw_durations: a level's duration marginal is the pushforward of a
    uniform draw over its (base, eta) combinations through max(1, round(base*eta)), so a duration's
    probability is its combination multiplicity over the combo count. Instead of drawing each of the
    n worlds independently (which at n=10 routinely clumps and leaves gaps), LHS stratifies each
    level's [0,1) probability axis into n equal slices, draws one duration per slice through the
    marginal's inverse CDF, and independently PERMUTES each level's n durations before pairing them
    into worlds. Two consequences, both wanted here: every level's n durations track its true
    marginal far more tightly than an i.i.d. sample of the same size (so the SAA average is a
    lower-variance, still-unbiased estimate of E[F]), and the independent permutations keep the
    levels decorrelated, matching the law's independence across levels.

    A degenerate level (single possible duration, e.g. local-1) contributes that value to all n
    worlds. Drawn ONCE from the caller's rng and then held fixed by the trainer, so this stays SAA.
    It also serves the frozen evaluation sample: with config.EVAL_SAMPLING == "lhs" (the current
    ruler), sample_scenarios delegates its draw here, from a separate rng stream than the trainer's.
    """
    from collections import Counter
    rows = list(disrupted.itertuples(index=False))
    levels = sorted({(r.road_class, int(r.severity)) for r in rows})
    cols = {}
    for lvl in levels:
        cnt = Counter(max(1, int(round(base * eta)))
                      for base in P.DURATION_SUPPORT[lvl] for eta in P.ETA)
        durs = sorted(cnt)
        cdf = np.cumsum([cnt[d] for d in durs], dtype=float) / sum(cnt.values())
        # one stratified draw per equal-probability slice: u in slice k is (k + jitter)/n, then
        # inverse-CDF (first duration whose cumulative probability exceeds u).
        us = (np.arange(n) + rng.rand(n)) / n
        col = np.array([durs[int(np.searchsorted(cdf, u, side="right"))] for u in us], dtype=int)
        rng.shuffle(col)                                   # decorrelate this level from the others
        cols[lvl] = col
    return [{int(r.edge_id): int(cols[(r.road_class, int(r.severity))][i]) for r in rows}
            for i in range(n)]


def worst_case_durations(disrupted):
    """The longest duration each segment can realize under the full model, i.e. the per-level
    maximum over every (base, efficiency) outcome. Used to size a horizon that no sampled
    training world can overrun."""
    per_level = {lvl: max(max(1, int(round(base * eta))) for base in support for eta in P.ETA)
                 for lvl, support in P.DURATION_SUPPORT.items()}
    return {int(r.edge_id): per_level[(r.road_class, int(r.severity))]
            for r in disrupted.itertuples(index=False)}
